import type { CSSProperties } from "react";
import { colors, font, radii, space } from "./design";

export const styles: Record<string, CSSProperties> = {
  container: {
    fontFamily: font.family,
    minWidth: 360,
    maxWidth: 420,
    padding: space.lg,
    color: colors.accentBlack,
    backgroundColor: colors.backgroundBase,
  },
  header: {
    marginBottom: space.md,
  },
  title: {
    margin: 0,
    fontSize: font.size.xl,
    fontWeight: font.weight.semibold,
    letterSpacing: -0.1,
  },
  headerSubtitle: {
    marginTop: space.xs,
    display: "flex",
    flexDirection: "column",
    gap: space.xs,
    maxWidth: "100%",
  },
  headerSubtitleTitle: {
    fontSize: font.size.sm,
    color: colors.blackAlpha72,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  headerSubtitleUrl: {
    fontSize: font.size.xs,
    color: colors.blackAlpha40,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  apiSection: {
    marginBottom: space.lg,
  },
  apiEditor: {
    display: "flex",
    flexDirection: "column",
    gap: space.xs,
  },
  apiLabel: {
    fontSize: font.size.sm,
    fontWeight: font.weight.medium,
    color: colors.blackAlpha72,
  },
  card: {
    borderRadius: radii.md,
    padding: space.md,
    marginBottom: space.md,
    backgroundColor: colors.backgroundLighter,
    boxShadow: `0 12px 32px rgba(38, 38, 38, 0.06), inset 0 0 0 1px ${colors.borderFaint}`,
  },
  cardHeader: {
    marginBottom: space.sm,
    overflow: "hidden",
  },
  cardTitle: {
    margin: 0,
    fontSize: font.size.md,
    fontWeight: font.weight.semibold,
    letterSpacing: -0.1,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    maxWidth: "100%",
  },
  cardSubtitle: {
    margin: `${space.xs}px 0 0`,
    fontSize: font.size.xs,
    color: colors.blackAlpha56,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  input: {
    width: "100%",
    padding: `${space.sm}px ${space.md}px`,
    borderRadius: radii.sm,
    border: `1px solid ${colors.borderMuted}`,
    fontSize: font.size.sm,
    backgroundColor: colors.backgroundBase,
    color: colors.accentBlack,
    boxSizing: "border-box",
  },
  select: {
    width: "100%",
    padding: `${space.sm}px ${space.md}px`,
    borderRadius: radii.sm,
    border: `1px solid ${colors.borderMuted}`,
    fontSize: font.size.sm,
    backgroundColor: colors.backgroundBase,
    color: colors.accentBlack,
    boxSizing: "border-box",
  },
  textarea: {
    width: "100%",
    padding: `${space.sm}px ${space.md}px`,
    borderRadius: radii.sm,
    border: `1px solid ${colors.borderMuted}`,
    fontSize: font.size.sm,
    resize: "vertical",
    backgroundColor: colors.backgroundBase,
    color: colors.accentBlack,
    boxSizing: "border-box",
  },
  helper: {
    margin: `${space.xs}px 0 0`,
    fontSize: font.size.xs,
    color: colors.blackAlpha56,
  },
  apiStatusRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: space.sm,
  },
  apiActions: {
    display: "flex",
    alignItems: "center",
    gap: space.sm,
    marginTop: space.sm,
  },
  successPill: {
    display: "inline-flex",
    alignItems: "center",
    gap: space.xs,
    padding: `${space.xs}px ${space.sm}px`,
    borderRadius: radii.lg,
    backgroundColor: colors.successTint,
    color: colors.success,
    fontSize: font.size.xs,
    fontWeight: font.weight.medium,
  },
  viewToggle: {
    display: "inline-flex",
    alignItems: "center",
    gap: space.xs,
    margin: `0 auto ${space.md}px`,
    padding: space.xs,
    borderRadius: radii.md,
    backgroundColor: "#f4f4f5",
    border: `1px solid ${colors.borderFaint}`,
    width: "fit-content",
  },
  viewButton: {
    padding: `${space.sm}px ${space.lg}px`,
    borderRadius: radii.sm,
    border: "none",
    backgroundColor: "transparent",
    fontSize: font.size.sm,
    fontWeight: font.weight.medium,
    cursor: "pointer",
    color: colors.blackAlpha64,
    transition: "all 150ms ease",
    display: "flex",
    alignItems: "center",
    gap: space.xs,
    minWidth: 80,
    justifyContent: "center",
  },
  viewButtonActive: {
    backgroundColor: "#ffffff",
    color: colors.accentBlack,
    boxShadow: "0 6px 14px rgba(38, 38, 38, 0.12)",
    fontWeight: font.weight.medium,
  },
  primaryButton: {
    width: "100%",
    padding: `${space.sm}px ${space.md}px`,
    borderRadius: radii.sm,
    border: "none",
    backgroundColor: colors.heat100,
    color: colors.backgroundLighter,
    fontSize: font.size.md,
    fontWeight: font.weight.medium,
    cursor: "pointer",
    boxShadow: "0 4px 12px rgba(250, 93, 25, 0.2)",
  },
  primaryButtonSmall: {
    padding: `${space.xs}px ${space.md}px`,
    borderRadius: radii.sm,
    border: "none",
    backgroundColor: colors.heat100,
    color: colors.backgroundLighter,
    fontSize: font.size.sm,
    fontWeight: font.weight.medium,
    cursor: "pointer",
    boxShadow: "0 5px 16px rgba(250, 93, 25, 0.2)",
  },
  toast: {
    position: "fixed",
    left: "50%",
    bottom: space.xl,
    transform: "translateX(-50%)",
    padding: `${space.sm}px ${space.lg}px`,
    borderRadius: radii.lg,
    backgroundColor: colors.accentBlack,
    color: colors.backgroundLighter,
    fontSize: font.size.sm,
    fontWeight: font.weight.medium,
    boxShadow: "0 12px 32px rgba(38, 38, 38, 0.25)",
    zIndex: 9999,
  },
  primaryButtonBusy: {
    opacity: 0.8,
    cursor: "default",
  },
  secondaryButton: {
    padding: `${space.xs}px ${space.md}px`,
    borderRadius: radii.sm,
    border: `1px solid ${colors.borderMuted}`,
    backgroundColor: colors.backgroundBase,
    color: colors.blackAlpha72,
    fontSize: font.size.sm,
    fontWeight: font.weight.medium,
    cursor: "pointer",
    boxShadow: `inset 0 0 0 1px ${colors.borderMuted}`,
  },
  linkButton: {
    padding: 0,
    border: "none",
    background: "none",
    color: colors.heat100,
    cursor: "pointer",
    fontSize: font.size.xs,
    fontWeight: font.weight.medium,
  },
  microcopy: {
    margin: `${space.xs}px 0 0`,
    fontSize: font.size.xs,
    color: colors.blackAlpha56,
  },
  error: {
    marginTop: space.sm,
    fontSize: font.size.xs,
    color: colors.danger,
    backgroundColor: colors.dangerTint,
    padding: `${space.xs}px ${space.sm}px`,
    borderRadius: radii.sm,
  },
  success: {
    marginTop: space.sm,
    fontSize: font.size.xs,
    color: colors.success,
    backgroundColor: colors.successTint,
    padding: `${space.xs}px ${space.sm}px`,
    borderRadius: radii.sm,
  },
  formStack: {
    display: "flex",
    flexDirection: "column",
    gap: space.sm,
    marginTop: space.sm,
  },
  fieldLabel: {
    display: "flex",
    flexDirection: "column",
    gap: space.xs,
    fontSize: font.size.xs,
    fontWeight: font.weight.medium,
    color: colors.blackAlpha72,
  },
  fieldRow: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))",
    gap: space.sm,
    width: "100%",
  },
  disclosure: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: space.sm,
    padding: `${space.sm}px ${space.md}px`,
    borderRadius: radii.sm,
    border: `1px solid ${colors.borderFaint}`,
    backgroundColor: colors.backgroundLighter,
    cursor: "pointer",
    fontSize: font.size.sm,
    fontWeight: font.weight.medium,
    color: colors.blackAlpha72,
  },
  disclosureActive: {
    borderColor: colors.heat40,
    boxShadow: `inset 0 0 0 1px ${colors.heat40}`,
  },
  disclosureSummary: {
    color: colors.blackAlpha56,
    fontSize: font.size.xs,
    fontWeight: font.weight.medium,
  },
  optionsBody: {
    marginTop: space.sm,
    display: "flex",
    flexDirection: "column",
    gap: space.sm,
  },
  formatList: {
    listStyle: "none",
    padding: 0,
    margin: 0,
    display: "grid",
    gap: space.sm,
  },
  formatItem: {
    border: `1px solid ${colors.borderMuted}`,
    borderRadius: radii.sm,
    padding: space.sm,
    backgroundColor: colors.backgroundBase,
  },
  checkboxLabel: {
    display: "flex",
    alignItems: "center",
    gap: space.sm,
    fontSize: font.size.sm,
    fontWeight: font.weight.medium,
    color: colors.blackAlpha72,
  },
  checkGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))",
    gap: space.sm,
  },
  formatLabelGroup: {
    display: "flex",
    alignItems: "center",
    gap: space.xs,
  },
  formatLabelText: {
    fontSize: font.size.sm,
    fontWeight: font.weight.medium,
  },
  recommendedBadge: {
    padding: `${space.xs}px ${space.sm}px`,
    borderRadius: radii.lg,
    backgroundColor: colors.heat16,
    color: colors.heat100,
    fontSize: font.size.xs,
    fontWeight: font.weight.medium,
    border: `1px solid ${colors.heat40}`,
  },
  formatHelper: {
    margin: `${space.xs}px 0 0`,
    fontSize: font.size.xs,
    color: colors.blackAlpha56,
  },
  notice: {
    margin: 0,
    fontSize: font.size.xs,
    color: colors.warning,
    backgroundColor: colors.warningTint,
    padding: `${space.xs}px ${space.sm}px`,
    borderRadius: radii.sm,
  },
  resultHeader: {
    display: "flex",
    flexDirection: "column",
    gap: space.sm,
    marginBottom: space.sm,
  },
  resultHeading: {
    display: "flex",
    alignItems: "center",
    gap: space.sm,
  },
  resultBadge: {
    display: "inline-flex",
    alignItems: "center",
    padding: `${space.xs}px ${space.sm}px`,
    borderRadius: radii.lg,
    backgroundColor: colors.heat16,
    color: colors.heat100,
    fontSize: font.size.xs,
    fontWeight: font.weight.medium,
  },
  resultMeta: {
    fontSize: font.size.xs,
    color: colors.blackAlpha56,
  },
  resultActions: {
    display: "flex",
    gap: space.sm,
  },
  previewContainer: {
    display: "flex",
    flexDirection: "column",
    gap: space.xs,
  },
  preview: {
    margin: 0,
    padding: space.sm,
    maxHeight: 200,
    overflow: "auto",
    borderRadius: radii.sm,
    backgroundColor: colors.surfaceTint,
    border: `1px solid ${colors.borderMuted}`,
    fontSize: font.size.xs,
    whiteSpace: "pre-wrap",
  },
  crawlInfo: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: space.sm,
    marginTop: space.sm,
  },
  crawlText: {
    fontSize: font.size.sm,
    margin: 0,
    color: colors.blackAlpha72,
  },
  muted: {
    marginTop: space.xs,
    fontSize: font.size.xs,
    color: colors.blackAlpha56,
  },
  compactHeader: {
    marginBottom: space.md,
  },
  apiDomainRow: {
    display: "flex",
    alignItems: "center",
    gap: space.sm,
    fontSize: font.size.xs,
    color: colors.blackAlpha56,
  },
  keyIcon: {
    fontSize: font.size.sm,
  },
  domain: {
    flex: 1,
    fontWeight: font.weight.medium,
    color: colors.blackAlpha72,
  },
  editKeyButton: {
    padding: 0,
    border: "none",
    background: "none",
    color: colors.heat100,
    cursor: "pointer",
    fontSize: font.size.xs,
    fontWeight: font.weight.medium,
  },
  sectionDivider: {
    height: 1,
    backgroundColor: colors.borderFaint,
    margin: `${space.md}px 0`,
  },
  tertiaryButton: {
    padding: `${space.xs}px ${space.sm}px`,
    border: "none",
    background: "none",
    color: colors.blackAlpha72,
    fontSize: font.size.xs,
    cursor: "pointer",
    textDecoration: "underline",
    fontWeight: font.weight.medium,
  },
  crawlStatusRow: {
    display: "flex",
    alignItems: "center",
    gap: space.sm,
    marginTop: space.sm,
  },
  pollingIndicator: {
    fontSize: font.size.xs,
    color: colors.blackAlpha56,
    fontStyle: "italic",
  },
  credits: {
    fontSize: font.size.xs,
    color: colors.blackAlpha56,
    fontWeight: font.weight.medium,
  },
};
